### PR TITLE
Remove not needed files of old build script

### PR DESCRIPTION
**Pull request by ruditimmermans**

### CODE REVIEW

**Comment by Olf0** [comment]
When I reviewed PR #23, I noticed that this file was empty and unused, so I deleted it there (in PR #23) by [commit fa87c43](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/fa87c43ac57aac23b3daa8926bd8abd255eb88f8).
Thus closing this PR #24 un-merged.

**Comment by ruditimmermans** [comment]
I think you need to remove manual first the build as i dont make a new release i just have see here, it reports : 🌶  failed to delete release with id "59977774"  <- Resource not accessible by integration
🌶  failed to delete ref "refs/tags/master" <- Resource not accessible by integration

Mebay something wrong into cepri his repo settings...?

**Comment by Olf0** [comment]
> I think you need to remove manual first the build as i dont make a new release i just have see here, it reports : hot_pepper failed to delete release with id "59977774" <- Resource not accessible by integration hot_pepper failed to delete ref "refs/tags/master" <- Resource not accessible by integration
> 
> Mebay something wrong into cepri his repo settings...?

No, what is wrong is https://github.com/CepiPerez/filecase-sailfish/blame/master/.github/workflows/SailfishFilecaseBuild.yml#L54
There is no tag called `master`, only a branch called so.

**Comment by Olf0** [comment]
@ruditimmermans, what are you trying to achieve by https://github.com/CepiPerez/filecase-sailfish/blame/master/.github/workflows/SailfishFilecaseBuild.yml#L51-L56 ?

**Comment by Olf0** [comment]
And now it created a tag and release named `master`: https://github.com/CepiPerez/filecase-sailfish/releases/tag/master

Well, you may tray to enhance it and check if at least the attached RPMs work correctly.
I will try to fix the releases section manually, later.

**Pull request closed without merging**
