### PR TITLE
Fix action build script to make automatic new download able releases

### PR DESCRIPTION
**Pull request by ruditimmermans**
1. Fix action build script to make automatic new downloadable releases
2. Fix into .spec file the version number to build the correct version number into armv7hl builds
3. Change my new Github name into about screen
4. Fix the correct path to show the SD-Card
5. Update version number to 0.4-2
6. Remove not needed files of old build script

### CODE REVIEW

**Comment by Olf0** [comment]
Hi Rudi, I made some small changes; thank you for leaving "allow commits from maintainers" on, so I was able to do that.  For details, see my notes there.

This is looking good, although I have not tested it.  But I assume you have tested the generated RPM, right?

As noted in [my last comment at issue 16](https://github.com/CepiPerez/filecase-sailfish/issues/16#issuecomment-1059896711), please try to cover a single topic per PR, so all the commits for "Fix show SD-Card" ([0ed2aaa](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/0ed2aaadb148f5e687c0df8593de775e7c59095d), [572e3ef](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/572e3efc1228e3166bffa1462bbb2133c661105d), [5d2f25b](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/5d2f25b2987992f14cbf3678ad50fde096be4335), [9c693fe](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/9c693fe20de02d456559fcba970bbdf61180aa86), [3c35644](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/3c356446ac40e559c7a3aa258b074e9e77d7ffc0), [aa1e173](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/aa1e1736f15b36f180de576ec6820aed5fc3c5f5) and my [5e084f2](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/5e084f2aa84c309d01b3c2bea24f91dab5bdd4d9)) should have been placed into a separate PR.  Never mind, this is O.K. for now, and I also regularly forget to clearly separate different topics into different PRs.

BTW, because I was too lazy to check thoroughly if the `filecase.yaml` file is really used for generating the spec file, I applied all changes in both, as you did.  But we should really determine if that is the case and then either delete `filecase.yaml` or leave the spec file untouched (because it is auto-generated).  Actually I believe that `filecase.yaml` is unused and can be deleted (plus the corresponding note in the spec file), but would be glad if you check my suspicion.

Because this PR consists of a long commit series with much forth and back, please perform a *squash merge* (called "Squash and merge" here in the web-frontend, selectable by the down-arrow) of this PR #23, or do you prefer that I am doing this?

P.S.: And please re-view [the final result](https://github.com/CepiPerez/filecase-sailfish/pull/23/files) before squash-merging, I may have introduced typos or other nonsense by my commits.

**Review by Olf0 — APPROVED** [review]

**Comment by ruditimmermans** [comment]
Hi Olf0, Yes i have tested the automatic builds in my repo it is working as of this speperate PR's would be comming as i was doing everything on my repo webfront i guess.... please make shure you dont delete bad-style.py into the scripts file becoss then it would not build anymore, and alsi the bad-style.xml should not be removed. Yes please make this Squash and merge. 
Thanks!

Greetings,
Rudi

**Comment by Olf0** [comment]
> Yes i have tested the automatic builds in my repo 

Thank you for confirming.

> please make shure you dont delete bad-style.py into the scripts file becoss then it would not build anymore,

But your [PR 24 was removing `bad-style.py`](https://github.com/CepiPerez/filecase-sailfish/pull/24/files), too?!?  So it is already removed [in your master branch](https://github.com/ruditimmermans/filecase-sailfish/blob/master/).

> and alsi the bad-style.xml should not be removed.

[It is still there](https://github.com/ruditimmermans/filecase-sailfish/blob/master/bad-style.xml), I did not touch it.

> Yes please make this Squash and merge.

O.K., I will, when we have the `bad-style`-questions sorted out.

**Comment by ruditimmermans** [comment]
I have add it back yesterday there should be also a PR of that, and what i have see now on the lasted pr what was merged with my repo the bad-style.py was removed with this pr #fa87c43 on my repo i just have note this.

**Comment by Olf0** [comment]
> I have add it back yesterday there should be also a PR of that

No, there wasn't any.

> and what i have see now on the lasted pr what was merged with my repo the bad-style.py was removed with this pr #fa87c43 on my repo i just have note this.

[Commit fa87c43](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/fa87c43ac57aac23b3daa8926bd8abd255eb88f8) was performed by me.
O.K., I will add it back, although I cannot see, where it is still used.

**Comment by ruditimmermans** [comment]
Oh that's wierd, it would be used by the remove of the build before it makes a new one into the build script what i use there. I try removed yesterday and then it was not building anymore on my repo after i have add it back it was building again....

**Pull request merged**
